### ISSUE TITLE
Limit enso-assets' publish overwrite

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Core#74] opened 2018-10-17 14:23 UTC
This is  a **bug | feature request**. (could be seen as both)

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Every time I do a `composer update` or `composer require ...`, several of the files I had to modify are overwritten by the enso-assets publish. The publish in itself is required in several cases. So I believe it should exclude certain publishes (maybe host those under enso-assets-intial? 🤔 )

Namely (with reasons/examples why): 
- `resources/js/pages/auth/AuthForm.vue` (username instead of email as login basis)
- `resources/js/modules/enso/plugins/index.js` (my imports are always overwritten)
- `resources/js/core/structure/navbar/Navbar.vue` (custom logo & extra component)
- `resources/js/core/structure/PageHeader.vue` (extra component/logic)
- `resources/js/core/structure/navbar/ProfileControl.vue` (custom logic & dropdown with integrated Logout instead)

Especially as these are files that should rarely change I think that the overhead in not having them included in every update is minimal; while those are (except ProfileControl maybe?) the most likely components that have to be customized over time.

### Steps to Reproduce
1. Make changes to any of the files mentioned above
2. Add a new package

### Expected behavior

Package to be installed

### Actual behavior

Package installs; and (due to _aggressive_ enso-assets) certain core files are _reverted_

Thanks in advance for the consideration.

**Comment by aocneanu** [comment] 2018-10-18 09:39
>This is a bug

:) If i'm allowed a joke, you keep using this term **bug** but *I don't think it means what you think it means*.

The bug happens when the code is not producing the exact expected behaviour. If instead it does, it's not a bug, it can be o logic problem or whatever.

Now back to your issue:

>resources/js/modules/enso/plugins/index.js

the reason you have an `enso` prefix to the plugins folder is because that's where enso should load plugins.

use `resources/js/modules/local/pluglins` for your plugins. And then use `resources/app.js` to load your local resources.

>resources/js/core/structure/navbar/ProfileControl.vue
Maybe you could post some pics with the dropdown and maybe we can integrate it in the core

>resources/js/pages/auth/AuthForm.vue
resources/js/core/structure/navbar/Navbar.vue
resources/js/core/structure/PageHeader.vue

Any file from the UI could be at anytime customized. Maybe we should build a config where we can specify what files will be excepted from publish. But then we have 50 packages. And at some point all the FE resources will be moved on npm.

Something that you could do now would be creating in your resources la `local/core` folder following enso's folder structure and hold there the source files that you customized. Then add in your composer.json a new line after [this one](https://github.com/laravel-enso/Enso/blob/master/composer.json#L74) with `"cp -f -r resources/js/local/core resources/js/"` and you're done.

**Comment by aocneanu** [comment] 2018-10-19 12:51
I could still use a pic / gif for the dropdown. I'll close this until you decide to post one.

**Closed by aocneanu** 2018-10-19 12:51 UTC

**Comment by jlsjonas** [comment] 2018-10-25 13:37
ping @aocneanu (also waiting on a reply for https://github.com/laravel-enso/FormBuilder/issues/47#issuecomment-432122495 )

**Comment by aocneanu** [comment] 2018-10-25 15:18
I’m not convinced yet. I didn’t had the time to think it through either.
