### ISSUE TITLE
Framework doesn't handle multi-level menu well

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Core#91] opened 2019-01-21 14:00 UTC
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

![image](https://user-images.githubusercontent.com/932193/51478794-c63ca180-1d8c-11e9-942f-b20693895821.png)
adding a 2nd menu level breaks url changes, and (likely related/the cause) can't seem to find the correct action state on the 2nd item
![image](https://user-images.githubusercontent.com/932193/51478883-fa17c700-1d8c-11e9-8b40-bcc2f56bec3c.png)

Breadcrumbs do work, and the navigation does happen (though gets reverted on page refresh)

### Steps to Reproduce
1. Add a has_children menu entry to laravel-enso.com with as parent another has_children item
2. move/create a menu inside the newly created entry
3. navigate to it, notice the above

### Expected behavior

same behavior as single-level items

### Actual behavior

errors

**Comment by aocneanu** [comment] 2019-01-21 14:34
the problem is exactly the next line where the commit is not passed recursively.
(`updateActiveMenu(menu.children, commit)`)

I'm working on the new release now and this will be fixed as well

**Comment by jlsjonas** [comment] 2019-01-21 14:35
Oh wauw... I looked everywhere where it wasn't passed along... except within itself 😅 

Thanks!

**Comment by aocneanu** [comment] 2019-01-21 15:10
b23989fc164d18561b66221312387d0b12f04de2 is related, the params returned by `MenuController@store` were also wrong

**Comment by aocneanu** [comment] 2019-01-21 17:18
fixed in the new core.

**Closed by aocneanu** 2019-01-21 17:18 UTC
